languageCode = "ja"
title = "dddpga1"
theme = "anatole"

[params]
title = "dddpga1"
author = "dddpga1"
description = "my blog"
profilePicture = "images/profile.jpg"

[menu]

  [[menu.main]]
  name = "Home"
  weight = 100
  identifier = "home"
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
