languageCode = "ja"
title = "dddpga1"
theme = "diary"

[params]
title = "dddpga1"
author = "dddpga1"
description = "my blog"
profilePicture = ""

[[menu.main]]
name = "main"
weight = 100
identifier = "main"
url = "/"

[[menu.main]]
name = "posts"
weight = 200
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "about"
weight = 300
identifier = "about"
url = "/about/"
