languageCode = "ja"
title = "dddpga1"
theme = "anatole"

[params]
title = "dddpga1"
author = "dddpga1"
description = "my blog"
profilePicture = "images/profile.jpg"

[[menu.main]]
name = "main"
weight = 100
identifier = "main"
url = "/"

[[menu.main]]
name = "posts"
weight = 200
identifier = "posts"
url = "/posts"
